---
- name: Install and Upload Web-server
  hosts: my_servers
  become: yes

  vars:
    source_file: index.html
    destin_file: /var/www/html

  tasks:
  - name: Install Apache
    package: name=apache2

  - name: Upload Web-site
    copy:
      src: "{{ source_file }}"
      dest: "{{ destin_file }}"
      mode: 0644
    notify: Restart Apache

  - name: Start Service
    service: name=apache2 state=started enabled=yes

  handlers:
    - name: Restart Apache
      service:
        name: apache2
        state: restarted  